Fix missing optional parameter in fetch_executable_internal
During the refactor of #1243 an instance of the call to fetch_executable_internal
was missing a required parameter (bool $combined_run_compare). This
makes the judgedaemon crash when a submission debug package is
requested.

The error message is:

```
[Jan 11 20:21:16.415] judgedaemon[49]: error: Too few arguments to function fetch_executable_internal(), 4 passed in /opt/domjudge/judgehost/lib/judge/judgedaemon.main.php on line 782 and exactly 5 expected
```